# Site settings
email: nadege.griesser@gmail.com
url: https://macuisinesansglutennilactose.github.io
meta_author: Nadège Griesser

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: macuisinesansglutennilactose-

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff69b4 #HotPink
  primary-rgb: "255,105,180" 
  secondary: 8b3a62 #HotPink4 menu
  secondary-dark: 8b0a50  #DeepPink4 selected

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

t:
  fr:
    title: Ma cuisine
    skills: sans gluten ni lactose
    portfolio: Recettes
    about: À propos
    contact: contact
    name: Nom
    email: E-Mail
    message: Message
    send: Envoyer
    units:
      gram: g
      kilogram: kg
      milliliter: mL
      liter: L
  de:
    title: Kochen
    skills: gluten und laktosefrei
    portfolio: Rezepte
    about: Über mich
    contact: Kontakt
    name: Name
    email: E-Mail-Adresse
    message: Nachricht
    send: Absenden
    units:
      gram: g
      kilogram: kg
      milliliter: mL
      liter: L
      
kcal:
  butter: 717 / 100
  mascarpone: 407 / 100
  ricefloor: 366 / 100
  cornfloor: 349 / 100
  egg: 137 / 100
